name: Deploy documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  swagger-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build docs
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: docs/.vuepress/dist
